### ISSUE TITLE
High level description of spopt needed for meta release change log

### ISSUE THREAD

**Issue by sjsrey** [pysal/spopt#135]
We need something similar to what was done for `pysal/access` in [2.3.0](https://github.com/pysal/pysal/releases/tag/v2.3.0)

**Comment by jGaboardi** [comment]
@xf37 Here is a start for the release notes @sjsrey needs for pysal/pysal#1208. Since we are only releasing stuff for regionalization, would you be able to give a go at this? These notes are based on that of [`pysal/access`](https://github.com/pysal/pysal/releases/tag/v2.3.0) for `pysal v2.3.0`.

------------------

#### [`pysal/spopt`](https://pysal.org/spopt)
Providing methods for solving optimization problems with spatial data. Currently, regionalization methods are supported with planned support for facility location and transportation-oriented modeling.

- We implement ...
- We support ...

This `spopt.region` models implemented  include:

- ...
- ...

**Comment by jGaboardi** [comment]
Once complete the `pysal/spopt` notes need to be added to [the draft release notes for `v2.4.0-rc1`](https://github.com/pysal/pysal/issues/1208#issuecomment-762501470).

**Comment by sjsrey** [comment]
> Once complete the `pysal/spopt` notes need to be added to [the draft release notes for `v2.4.0-rc1`](https://github.com/pysal/pysal/issues/1208#issuecomment-762501470).

Changes should now be added as PR into https://github.com/pysal/pysal/blob/master/CHANGELOG.md

**Comment by xf37** [comment]
> @xf37 Here is a start for the release notes @sjsrey needs for [pysal/pysal#1208](https://github.com/pysal/pysal/issues/1208). Since we are only releasing stuff for regionalization, would you be able to give a go at this? These notes are based on that of [`pysal/access`](https://github.com/pysal/pysal/releases/tag/v2.3.0) for `pysal v2.3.0`.
> 
> #### [`pysal/spopt`](https://pysal.org/spopt)
> Providing methods for solving optimization problems with spatial data. Currently, regionalization methods are supported with planned support for facility location and transportation-oriented modeling.
> 
> * We implement ...
> * We support ...
> 
> This `spopt.region` models implemented include:
> 
> * ...
> * ...

Okay. I will try to finish it and ask for your comments.

**Comment by jGaboardi** [comment]
Resolving in pysal/pysal#1217
