### ISSUE TITLE
Example Notebook: LSCP 

### ISSUE THREAD

**Issue by erinrolson** [pysal/spopt#253]
![Screen Shot 2022-06-13 at 12 16 46 PM](https://user-images.githubusercontent.com/39073850/173398822-5f024a76-bb55-4fa4-9e85-10ed616938f8.png)

I was going through the [LSCP notebook](https://pysal.org/spopt/notebooks/lscp.html) in detail and am confused by section 19 "LSCP built from cost matrix". lscp_from_cost_matrix.facility_client_array() returns a NoneType object for me and I don't see anywhere in the notebook where results from this line are ever used. If I comment the line out the results still plot.

**Comment by jGaboardi** [comment]
Correct. This is due to [functionality](https://github.com/pysal/spopt/blob/abc3a764beec1ed6fcd02f4788b905076b7ef6a7/spopt/locate/coverage.py#L311-L312) that @gegen07 included last week that call the `{client_facility/facility_client}_array()` methods internally when solving. Moreover, nothing is returned when calling the `{client_facility/facility_client}_array()` methods because the [`cli2fac`](https://github.com/pysal/spopt/blob/abc3a764beec1ed6fcd02f4788b905076b7ef6a7/spopt/locate/base.py#L72) and [`fac2cli`](https://github.com/pysal/spopt/blob/abc3a764beec1ed6fcd02f4788b905076b7ef6a7/spopt/locate/coverage.py#L280) attributes are being set.

**Comment by jGaboardi** [comment]
@gegen07 This is something we should probably update in the notebooks.
