### ISSUE TITLE
Unable to run through LSCP example

### ISSUE THREAD

**Issue by Dekermanjian** [pysal/spopt#446]
I am trying to run the following example locally: https://pysal.org/spopt/notebooks/lscp_gis.html

At this point `lscp = lscp.solve(solver)` I get a `RuntimeError: Model is not solved: Infeasible. See ``pulp.constants.LpStatus`` for more information.` Can someone please try to reproduce the results of the example in the link above? I am not certain if this is a PuLP installation issue or something else?

**Comment by gegen07** [comment]
Hey @Dekermanjian!

Unfortunately, I am also getting this error. The `cost_matrix` of durations changed, I think some update on OSM routing service increased the values, and then the model with the same service radius resulted in an infeasible model. Try to increase the service radius and solve the model.

By inspecting the folium maps, I discovered some first aid stations changed their locations. The minnimum value to turn the model infeasible is 290, since it is the minimum acceptable value for one building in university of toronto.

**Comment by Dekermanjian** [comment]
Hey @gegen07 thank you for the quick response. I guess I am wondering why it would be infeasible. There is no limit to the number of first aid stations that can be situated if you situate a first aid station on every street then it should be within the constraint of walking from any building to the situated first aid station in 150 seconds (2 minutes and 30 seconds). The only solution as you said is when the radius is large enough such that all buildings can be serviced with 1 situated first aid station.

**Comment by gegen07** [comment]
You are right @Dekermanjian, but there are no aid stations in 150 seconds to cover a specific building. The aid stations changed over time since the last commit on the notebook. Then, if there are no aid stations in a service radius $X$ the restriction would not be attended and the model is infeasible.

**Comment by Dekermanjian** [comment]
I see, so for the solution to then become feasible I need to either:
1). Add more roads (represented as black points in the figure) or
2). Remove buildings (represented as blue points in the figure) that are outside the bounds of 150 seconds

Is there an easy way to identify which buildings are the ones that are producing an intractable equation?

**Comment by Dekermanjian** [comment]
@gegen07  never mind, I was able to do option 2 and it is now working again.

**Comment by Dekermanjian** [comment]
I added the highlighted line of code below to get it to work:
![image](https://github.com/pysal/spopt/assets/39779176/e3e41ac2-9bf2-4d52-a0b1-33f1e64a9874)

**Comment by jGaboardi** [comment]
@gegen07 Shall we update the demo notebook?
